//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Resources/InputSystem/GameInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInput"",
    ""maps"": [
        {
            ""name"": ""game map"",
            ""id"": ""8dbff33c-b04e-4d73-bce8-a5283e4ee7d5"",
            ""actions"": [
                {
                    ""name"": ""Axis"",
                    ""type"": ""Value"",
                    ""id"": ""021380d9-309e-4722-839c-e56c7029b431"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Value"",
                    ""id"": ""d1667510-3eb2-4173-9cd5-21fb0f9e565b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""WASD"",
                    ""type"": ""Value"",
                    ""id"": ""a1601e7e-7c54-4ec9-b1df-5ff5b188b4fd"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""shift"",
                    ""type"": ""Button"",
                    ""id"": ""3caee853-6971-49ca-b590-213120d1f0a2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ctrl"",
                    ""type"": ""Button"",
                    ""id"": ""dd94e753-2922-40c5-a86c-df394d225ef3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""jump"",
                    ""type"": ""Button"",
                    ""id"": ""16136fc2-d40f-4b36-804b-980637d0174e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Exit"",
                    ""type"": ""Button"",
                    ""id"": ""86183c2a-ad5c-4b50-b46d-249c6dc60a26"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Switch"",
                    ""type"": ""Button"",
                    ""id"": ""28d259c8-571b-4f76-97d0-50d63dc28878"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Fight"",
                    ""type"": ""Button"",
                    ""id"": ""f8640030-5920-4932-9580-1653adb0ab07"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""48772aaf-6cbc-42d0-bcf2-4dd92be513bd"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": ""Invert"",
                    ""groups"": """",
                    ""action"": ""Axis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""324ad6b6-6597-408f-886a-08900d9c466a"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""f5bc7765-a52e-4612-b97a-977e192a2514"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WASD"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""36c52012-84fc-4b15-9691-dcf5002f5a98"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WASD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""30a304a6-e9cc-42a7-bacd-3794e2dfb282"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WASD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9893186d-acf9-4dfa-b5ef-6675604a777d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WASD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""8977c8e7-22be-44d6-8d12-ad33a5827f02"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WASD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""96ee379b-1ca1-4f2c-9f12-3e629caa9611"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""shift"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f8420a60-8b00-49ce-89b5-eebc1a93ad0a"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ctrl"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cf90cc8f-dfd8-4c9b-9e88-b4e4f5bdb3b5"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9539cb37-0a5b-4570-aeba-ec527f61b954"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Exit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a27564fe-be83-4cd9-82aa-28f587098588"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e08c4ab0-1b83-44a1-8fe6-7f1e08fdfb95"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // game map
        m_gamemap = asset.FindActionMap("game map", throwIfNotFound: true);
        m_gamemap_Axis = m_gamemap.FindAction("Axis", throwIfNotFound: true);
        m_gamemap_Zoom = m_gamemap.FindAction("Zoom", throwIfNotFound: true);
        m_gamemap_WASD = m_gamemap.FindAction("WASD", throwIfNotFound: true);
        m_gamemap_shift = m_gamemap.FindAction("shift", throwIfNotFound: true);
        m_gamemap_ctrl = m_gamemap.FindAction("ctrl", throwIfNotFound: true);
        m_gamemap_jump = m_gamemap.FindAction("jump", throwIfNotFound: true);
        m_gamemap_Exit = m_gamemap.FindAction("Exit", throwIfNotFound: true);
        m_gamemap_Switch = m_gamemap.FindAction("Switch", throwIfNotFound: true);
        m_gamemap_Fight = m_gamemap.FindAction("Fight", throwIfNotFound: true);
    }

    ~@GameInput()
    {
        UnityEngine.Debug.Assert(!m_gamemap.enabled, "This will cause a leak and performance issues, GameInput.gamemap.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // game map
    private readonly InputActionMap m_gamemap;
    private List<IGamemapActions> m_GamemapActionsCallbackInterfaces = new List<IGamemapActions>();
    private readonly InputAction m_gamemap_Axis;
    private readonly InputAction m_gamemap_Zoom;
    private readonly InputAction m_gamemap_WASD;
    private readonly InputAction m_gamemap_shift;
    private readonly InputAction m_gamemap_ctrl;
    private readonly InputAction m_gamemap_jump;
    private readonly InputAction m_gamemap_Exit;
    private readonly InputAction m_gamemap_Switch;
    private readonly InputAction m_gamemap_Fight;
    public struct GamemapActions
    {
        private @GameInput m_Wrapper;
        public GamemapActions(@GameInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Axis => m_Wrapper.m_gamemap_Axis;
        public InputAction @Zoom => m_Wrapper.m_gamemap_Zoom;
        public InputAction @WASD => m_Wrapper.m_gamemap_WASD;
        public InputAction @shift => m_Wrapper.m_gamemap_shift;
        public InputAction @ctrl => m_Wrapper.m_gamemap_ctrl;
        public InputAction @jump => m_Wrapper.m_gamemap_jump;
        public InputAction @Exit => m_Wrapper.m_gamemap_Exit;
        public InputAction @Switch => m_Wrapper.m_gamemap_Switch;
        public InputAction @Fight => m_Wrapper.m_gamemap_Fight;
        public InputActionMap Get() { return m_Wrapper.m_gamemap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GamemapActions set) { return set.Get(); }
        public void AddCallbacks(IGamemapActions instance)
        {
            if (instance == null || m_Wrapper.m_GamemapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GamemapActionsCallbackInterfaces.Add(instance);
            @Axis.started += instance.OnAxis;
            @Axis.performed += instance.OnAxis;
            @Axis.canceled += instance.OnAxis;
            @Zoom.started += instance.OnZoom;
            @Zoom.performed += instance.OnZoom;
            @Zoom.canceled += instance.OnZoom;
            @WASD.started += instance.OnWASD;
            @WASD.performed += instance.OnWASD;
            @WASD.canceled += instance.OnWASD;
            @shift.started += instance.OnShift;
            @shift.performed += instance.OnShift;
            @shift.canceled += instance.OnShift;
            @ctrl.started += instance.OnCtrl;
            @ctrl.performed += instance.OnCtrl;
            @ctrl.canceled += instance.OnCtrl;
            @jump.started += instance.OnJump;
            @jump.performed += instance.OnJump;
            @jump.canceled += instance.OnJump;
            @Exit.started += instance.OnExit;
            @Exit.performed += instance.OnExit;
            @Exit.canceled += instance.OnExit;
            @Switch.started += instance.OnSwitch;
            @Switch.performed += instance.OnSwitch;
            @Switch.canceled += instance.OnSwitch;
            @Fight.started += instance.OnFight;
            @Fight.performed += instance.OnFight;
            @Fight.canceled += instance.OnFight;
        }

        private void UnregisterCallbacks(IGamemapActions instance)
        {
            @Axis.started -= instance.OnAxis;
            @Axis.performed -= instance.OnAxis;
            @Axis.canceled -= instance.OnAxis;
            @Zoom.started -= instance.OnZoom;
            @Zoom.performed -= instance.OnZoom;
            @Zoom.canceled -= instance.OnZoom;
            @WASD.started -= instance.OnWASD;
            @WASD.performed -= instance.OnWASD;
            @WASD.canceled -= instance.OnWASD;
            @shift.started -= instance.OnShift;
            @shift.performed -= instance.OnShift;
            @shift.canceled -= instance.OnShift;
            @ctrl.started -= instance.OnCtrl;
            @ctrl.performed -= instance.OnCtrl;
            @ctrl.canceled -= instance.OnCtrl;
            @jump.started -= instance.OnJump;
            @jump.performed -= instance.OnJump;
            @jump.canceled -= instance.OnJump;
            @Exit.started -= instance.OnExit;
            @Exit.performed -= instance.OnExit;
            @Exit.canceled -= instance.OnExit;
            @Switch.started -= instance.OnSwitch;
            @Switch.performed -= instance.OnSwitch;
            @Switch.canceled -= instance.OnSwitch;
            @Fight.started -= instance.OnFight;
            @Fight.performed -= instance.OnFight;
            @Fight.canceled -= instance.OnFight;
        }

        public void RemoveCallbacks(IGamemapActions instance)
        {
            if (m_Wrapper.m_GamemapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGamemapActions instance)
        {
            foreach (var item in m_Wrapper.m_GamemapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GamemapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GamemapActions @gamemap => new GamemapActions(this);
    public interface IGamemapActions
    {
        void OnAxis(InputAction.CallbackContext context);
        void OnZoom(InputAction.CallbackContext context);
        void OnWASD(InputAction.CallbackContext context);
        void OnShift(InputAction.CallbackContext context);
        void OnCtrl(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnExit(InputAction.CallbackContext context);
        void OnSwitch(InputAction.CallbackContext context);
        void OnFight(InputAction.CallbackContext context);
    }
}
